### PR TITLE
Compiler: more blocks, more debug

### PR DESCRIPTION
**Pull request by hhugo**

### CODE REVIEW

**Comment by hhugo** [comment]
I'm not sure this should be merged, I don't remember why I disabled this code previously.

**Comment by hhugo** [comment]
It's not clear to me why the lambda_lifting test is affected this way.

**Comment by vouillon** [comment]
> It's not clear to me why the lambda_lifting test is affected this way.

If you have more blocks, the CPS transform will generate more functions. Since inlining is disabled for this test, you see them in the output.

**Comment by vouillon** [comment]
We need to have debugging information only for the locations where the JavaScript debugger might stop, which does not necessarily corresponds to where the OCaml debugger would stop. So it is not clear to me that we need more.

**Comment by hhugo** [comment]
> > It's not clear to me why the lambda_lifting test is affected this way.
> 
> If you have more blocks, the CPS transform will generate more functions. Since inlining is disabled for this test, you see them in the output.

That doesn't explain why `g` is no longer lifted.

**Comment by vouillon** [comment]
> > > It's not clear to me why the lambda_lifting test is affected this way.
> > 
> > 
> > If you have more blocks, the CPS transform will generate more functions. Since inlining is disabled for this test, you see them in the output.
> 
> That doesn't explain why `g` is no longer lifted.

This is probably because there are now two consecutive function definitions. They are not lifted, in case they are mutually recursive.

**Pull request closed without merging**
