### PR TITLE
Bugfix in ocamlyacc runtime code 

### PR DESCRIPTION
**Pull request by mlasson**
# Description 

The parsing module runtime has a bug in `parsing.js`. 

In happened in the "ERROR_DETECTED" case. 
There's a break instruction that is breaking a for loop instead of breaking a switch. 
Which makes the "flow" fall through the "SHIFT" case instead of the "SHIFT_RECOVER" case. 

This PR adds a label to fix this. 

Here is a reproduction case, https://github.com/mlasson/js-yacc-bug

### CODE REVIEW

**Comment by hhugo** [comment]
Can we include the repro case as well ?

**Comment by mlasson** [comment]
Where do you want to include it ?
In a PR description ? In a test ? In a comment ?
But, sure, yes, feel free.

**Comment by mlasson** [comment]
> Where do you want to include it ? In a PR description ? In a test ? In a comment ? But, sure, yes, feel free.

I can add a test myself if you want. In that case, should I add a directory `tests-ocamlyacc` in the `compiler` directory ?

**Comment by hhugo** [comment]
I 

> > Where do you want to include it ? In a PR description ? In a test ? In a comment ? But, sure, yes, feel free.
> 
> I can add a test myself if you want. In that case, should I add a directory `tests-ocamlyacc` in the `compiler` directory ?

Adding it in compiler/tests-jsoo would make it run in both native and js. I would also be a good place to make sure https://github.com/ocsigen/js_of_ocaml/pull/1308 follows the native version.

**Comment by hhugo** [comment]
@mlasson, Gentle ping

**Comment by hhugo** [comment]
Adding test in https://github.com/ocsigen/js_of_ocaml/pull/1315

**Comment by mlasson** [comment]
Thanks

**Pull request merged**
