### PR TITLE
Runtime: Rewrite bigarray stubs

### PR DESCRIPTION
**Pull request by hhugo**
- rewrite most of the bigarray runtime
- remove the stale typescript implementation (`bigarray.ts`)
- Import bigarray tests from the ocaml repo and make tests pass
- add support for marshaling bigarrays

### CODE REVIEW

**Comment by hhugo** [comment]
@andrewray do you have any interest reviewing this ? (as you wrote the first bigarray support)

**Comment by hhugo** [comment]
@avsm, @dbuenzli do you have anything (apps,tests) bigarray dependent that you could test against this PR ?

**Comment by dbuenzli** [comment]
Sorry @hhugo it seems the bits that I needed that for were eventually (re?)written in JavaScript and none of my jsoo apps are currently using bigarrays. 

But thanks for the work this is very much appreciated. Does it also enshrine the fact that they became part of the stdlib ? (i.e. no longer need to `+bigarray` ?)

**Comment by hhugo** [comment]
`bigarray.js` was already part of the `runtime.js` provided by js_of_ocaml.

Importing bigarray's tests from the ocaml testsuite has proven very useful. It revealed various bugs in the previous implementation.

**Comment by hhugo** [comment]
@TyOverby, I did some cleanup and added few more tests there
https://github.com/ocsigen/js_of_ocaml/pull/879/files#diff-9a9f37a69ccabbe8df4214bde64f4ff1

**Comment by avsm** [comment]
@hhugo Mirage uses Bigarray fairly extensively, and in particular, the Irmin team have been experimenting with compiling it to JS.  So CCing in @craigfe @samoht @pascutto to see if they can test this

**Pull request merged**
