### PR TITLE
Switch tests to 4.13

### PR DESCRIPTION
**Pull request by hhugo**

### CODE REVIEW

**Comment by hhugo** [comment]
@smorimoto, can I test OCaml 4.13-rc with setup-ocaml ?

**Comment by smorimoto** [comment]
@hhugo I just pushed a commit to enable `4.13-rc`!

**Comment by hhugo** [comment]
Thanks

**Comment by smorimoto** [comment]
Can we disable the test for 4.12? If so, I can push an additional commit.

**Comment by hhugo** [comment]
Tests are supposed to pass on 4.12 in this PR

**Comment by smorimoto** [comment]
That's good!

**Comment by hhugo** [comment]
@smorimoto, have I broken something during rebase ? do you expect the missing compiler for windows ?

**Comment by smorimoto** [comment]
@hhugo Maybe -- Yes, 4.13 is not yet available on Windows, so you should set it to `4.12.x`.

**Pull request merged**
