### PR TITLE
Compat with Tyxml 4.0

### PR DESCRIPTION
**Pull request by Drup**
Most of the work was done by @vasilisp

### CODE REVIEW

**Comment by Drup** [comment]
Tyxml is being released! @hhugo you can merge!

**Comment by vasilisp** [comment]
Can we merge this and the corresponding branches for Eliom et al.?

I have quite a few Eliom branches that do not merge cleanly, and maintaining them really gets in the way...

**Comment by hhugo** [comment]
Should we drop compat with ocaml 4.00 and 4.01 entirely ?
@vouillon, @balat ?

**Comment by Drup** [comment]
I personally think it's fine, it would allow to migrate jsoo's core to ppx too, which would be nice.

**Pull request merged**
