### PR TITLE
Fix syntax extension tests.

### PR DESCRIPTION
**Pull request by Drup**

### CODE REVIEW

**Comment by Drup** [comment]
@hhugo Do you have other things ongoing ? I think we should cut a release for ppx/4.02.2.

**Comment by hhugo** [comment]
few things that can wait. We should do a release soon. I'll try to update the CHANGELOG

**Comment by Drup** [comment]
(Don't forgot to merge that :D)

**Comment by Drup** [comment]
ping for the release ?

**Pull request merged**
