### PR TITLE
Runtime: change representation of int64 

### PR DESCRIPTION
**Pull request by hhugo**
Before we can merge this PR,
- we need to release 3.5.0 first
- update packages that depend on the current representation

- [x] zarith_js_stubs
- [x] update base

### CODE REVIEW

**Comment by TyOverby** [comment]
What is the motivation behind the change?  Speed?  Correctness?

**Comment by hhugo** [comment]
Uniformity, I'd like to treat int64 as any other custom block. I'm not sure what's the impact on performance.

**Comment by vouillon** [comment]
`Js_of_ocaml.Json` will no longer work with these values, though...

**Comment by hhugo** [comment]
@vouillon, I've update the PR to restore compatibility with `Js_of_ocaml.Json` and `ppx_deriving_json`

**Comment by hhugo** [comment]
@vouillon, any objections for merging this ?

**Comment by vouillon** [comment]
No objection

**Pull request merged**
