### PR TITLE
Deriving OCaml 4.03

### PR DESCRIPTION
**Pull request by hhugo**

### CODE REVIEW

**Comment by hhugo** [comment]
We need to add some tests: https://gist.github.com/vasilisp/187ea176382511db3146 (https://github.com/ocsigen/js_of_ocaml/pull/364)

**Comment by vasilisp** [comment]
Thanks! Looks good from a first glance. I will test and try to integrate the tests in the build system.

**Comment by vasilisp** [comment]
This has a runtime dependency on `deriving`. I have a [messy patch](https://github.com/ocsigen/deriving/tree/4.03) to compile `deriving` on 4.03, but it breaks older versions. (I am still trying to figure out how to preserve compatibility.)

**Comment by vasilisp** [comment]
I pushed a few fixes for inline records. To my knowledge, it works now.

**Comment by hhugo** [comment]
thanks

**Comment by hhugo** [comment]
I've added some tests.. merging

**Pull request merged**
