### PR TITLE
Add Style Declaration Property Accessors

### PR DESCRIPTION
**Pull request by TyOverby**
These APIs allow direct access to the declarations programatically.  They are especially useful for setting [css custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties).

- [CSSStyleDeclaration.setProperty](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/setProperty)
- [CSSStyleDeclaration.getPropertyValue](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/getPropertyValue)
- [CSSStyleDeclaration.getPropertyPriority](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/getPropertyPriority)
- [CSSStyleDeclaration.removeProperty](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/removeProperty)

### CODE REVIEW

**Comment by smorimoto** [comment]
Just needs a CHANGELOG entry

**Comment by smorimoto** [comment]
By the way, every time I wonder how good it is to force us to just copy and paste the spec.
I think it's a better idea to auto-generate these based on something like WenIDL.

**Comment by TyOverby** [comment]
@smorimoto Changelog updated!

As for generating the API from webidl, a coworker of mine @pmwhite is doing exactly that!

**Comment by smorimoto** [comment]
That's great! Generating it from WebIDL or TypeScript resources is always a good thing!
Perhaps another easy way is to reuse the ts2ocaml library and generate it. In fact, we created a standard library based on it.
So either way, it should work well!

**Pull request merged**
