### PR TITLE
adds the intersection observer API

### PR DESCRIPTION
**Pull request by TyOverby**
The Intersection Observer API provides a way to asynchronously observe
    changes in the intersection of a target element with an ancestor element or
    with a top-level document's viewport.
    https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API

### CODE REVIEW

**Comment by TyOverby** [comment]
@hhugo it looks like one of the failures is because of a flaky http request that failed for unkown reasons.

The other appears to be an ocamlformat failure, but I don't see an ocamlformat file in this repo.  How should I fix this?

**Comment by hhugo** [comment]
https://github.com/ocsigen/js_of_ocaml/blob/master/.ocamlformat

You need to have ocamlformat installed with the right version and do `make fmt`

**Comment by TyOverby** [comment]
@hhugo ah great; that wasn't hard.  For some reason I thought that you needed a ".ocamlformat" file at the root.

**Comment by hhugo** [comment]
There is an .ocamlformat at the root

**Pull request merged**
