### PR TITLE
Fix ci mac

### PR DESCRIPTION
**Pull request by hhugo**

### CODE REVIEW

**Comment by vouillon** [comment]
I suspect we can just remove this code now.

**Comment by hhugo** [comment]
What makes you say that ?
I would imagine that we should wait on https://github.com/actions/runner-images/issues/10984

**Comment by hhugo** [comment]
Are you sure this is not working just because of caches ?
I see in your branch that you've removed the previous fix https://github.com/ocaml-wasm/wasm_of_ocaml/pull/131/commits/4ee156ef024e5e32b6ae1ba3f2946d81d70be7dd https://github.com/ocsigen/js_of_ocaml/pull/1737 but this PR and an attempt to fix the fix :)

**Comment by vouillon** [comment]
That's what I meant. You can probably just remove the previous fix.

This job is failing without the initial fix: https://github.com/ocsigen/js_of_ocaml/actions/runs/11916809033/job/33210339357
image

The initial fix no longer work for this job: https://github.com/ocsigen/js_of_ocaml/actions/runs/12012253626/job/33483052722
image

And this jobs was already using the newer image, at a much earlier date: https://github.com/coq/platform/actions/runs/11838273102/job/32987032575
image

**Comment by hhugo** [comment]
https://github.com/ocsigen/js_of_ocaml/pull/1746

**Pull request merged**
