### PR TITLE
Remove json polyfill

### PR DESCRIPTION
**Pull request by hhugo**

### CODE REVIEW

**Comment by hhugo** [comment]
Does anyone know if this JSON poly-fill is safe to drop  ?

**Comment by dbuenzli** [comment]
According to [caniuse](https://caniuse.com/#feat=json) I would say yes but maybe it's better to ask the person who introduced it in the first place.

**Comment by hhugo** [comment]
@vouillon, @balat, would you be able to tests this PR ? Do you think it's OK to drop this poly-fill ?

**Comment by balat** [comment]
Yes we can safely remove it. Even NodeJS has it and it is something very standard.

**Pull request merged**
