### PR TITLE
Add support for OCaml 4.12

### PR DESCRIPTION
**Pull request by kit-ty-kate**
`Const_pointer` was removed in https://github.com/ocaml/ocaml/commit/0d44a6cfe6ac328165dced897f23e431f2e503b0

### CODE REVIEW

**Review by jrochel — APPROVED** [review]

**Comment by kit-ty-kate** [comment]
Are there any plans for releasing js_of_ocaml with OCaml 4.12 support by any chance? The compiler is currently in beta2 and we hope to get it released mid February at the latest. It would be really nice to have js_of_ocaml available in advance for extra testing.

**Comment by kit-ty-kate** [comment]
Any news on a potential release?

**Comment by hhugo** [comment]
I don't have access to my usual setup. I can't promise anything but i'll try to do something tonight

**Comment by hhugo** [comment]
https://github.com/ocaml/opam-repository/pull/18160

**Pull request merged**
