### PR TITLE
Small changes wrt compiler-libs.

### PR DESCRIPTION
**Pull request by Drup**
Tiny cleanup that makes
- the code a bit cleaner
- js_of_ocaml plays more nicely with my WIP fork :p

This compiles under 4.00.1

### CODE REVIEW

**Comment by vasilisp** [comment]
Looks good. Your fork of what? Eliom?

**Comment by Drup** [comment]
Yes. :3

**Comment by Drup** [comment]
In general, treating `Ident.t` as an abstract datatype is a good idea.

**Comment by hhugo** [comment]
There are more places that should be cleaned in we start linking compilier-libs [1]. 
I don't know the reason for not having compiler-libs linked already.. 

@drup What does your eliom fork have to do with this change ? 

[1] https://github.com/ocsigen/js_of_ocaml/search?utf8=%E2%9C%93&q=%22copied+from%22+parse_bytecode.ml&type=Code

**Comment by Drup** [comment]
@hhugo Among some other changes, I made `Ident.t` abstract (for various reasons that are a bit long to detail here). I will take the time to do the other changes.

**Comment by hhugo** [comment]
If anyone's wondering, this is to play nicely with an ocaml compiler fork tuned for eliom

**Comment by Drup** [comment]
@hhugo Thanks!

**Pull request closed without merging**
