### PR TITLE
Separate compilation: Link only what we need

### LINKED ISSUE #943: [FEATURE REQUEST] Separate compilation: only link modules that are needed (like ocamlc)

### LINKED ISSUE #1316: Compiler: Remove mutable fields from Source_map.t

### PR DESCRIPTION
**Pull request by hhugo**
Fix #943 and #1375
- `js_of_ocaml link` now accept a `--linkall` flags.
-  cma files are now compiled one compilation unit / module at a time. We no longer perform cross-module optimization with separate compilation. All compilation units of a cma are still stored in a single file.
- We only warn about `Warning: your program contains effect handlers; you should probably run js_of_ocaml with option '--enable=effects' if the offending module end up being linked.
- The resulting files should be much reduced (sourcemap is shrinked as well)
- In addition, this PR fix sourcemap with separate compilation and fix #1316 

ISSUE 
- The dune rules for separate compilation currently completely ignore `-linkall` information. In practice, with this PR, it means that inline_tests are broken because the library containing the tests is no longer linked.

TODO
- [x] check that sourcemap are still correct.

### CODE REVIEW

**Comment by hhugo** [comment]
Dune integration discussed in https://github.com/ocaml/dune/pull/6832

**Comment by hhugo** [comment]
@pmwhite @TyOverby, could you check this PR ? You should look at artifact sizes and compilation times with separate compilation. Compilation rules will need to be updated to propagate `-linkall` to `js_of_ocaml link`

**Comment by pmwhite** [comment]
This is an exciting patch. I can test this out, hopefully sometime today.

**Comment by pmwhite** [comment]
I'm getting the following build warnings from this patch:
```
Warning: '--source-map' is enabled but the bytecode program was compiled with no debugging information.
Warning: Consider passing '-g' option to ocamlc.
```
I'm assuming this patch has changed something to cause those messages to be printed, since we weren't getting these warnings before. Is this new warning expected? If so, what is the right response? One obvious answer is to add `-g` like the message says, but that has its own set of trade-offs.

**Comment by pmwhite** [comment]
Oh, it's worth saying that I didn't get to the point of adding the `linkall` flag to the build yet; maybe that error goes away if I add the flag?

**Comment by hhugo** [comment]
> I'm getting the following build warnings from this patch:
> 
> ```
> Warning: '--source-map' is enabled but the bytecode program was compiled with no debugging information.
> Warning: Consider passing '-g' option to ocamlc.
> ```
> 
> I'm assuming this patch has changed something to cause those messages to be printed, since we weren't getting these warnings before. Is this new warning expected? If so, what is the right response? One obvious answer is to add `-g` like the message says, but that has its own set of trade-offs.

This warning is not new. it used to trigger on empty cma but it was fixed quite sometime ago. I suspect that it now triggers because we compile module from a cma individually and one of the module doesn't have debug info.

**Comment by pmwhite** [comment]
> This warning is not new. it used to trigger on empty cma but it was fixed quite sometime ago. I suspect that it now triggers because we compile module from a cma individually and one of the module doesn't have debug info.

I see. If I understand right, this is a bug in this PR, since it is okay for individual modules to not have any debug info.

**Comment by hhugo** [comment]
> > This warning is not new. it used to trigger on empty cma but it was fixed quite sometime ago. I suspect that it now triggers because we compile module from a cma individually and one of the module doesn't have debug info.
> 
> I see. If I understand right, this is a bug in this PR, since it is okay for individual modules to not have any debug info.

It's ok but could result in worse sourcemap. One could argue that the warning is correct. Is there a good reason for omitting the -g for some modules only ?

**Comment by hhugo** [comment]
> > Is there a good reason for omitting the -g for some modules only ?
> 
> I'm assuming our build system doesn't selectively omit -g (I'll double-check this assumption; EDIT: assumption seems correct), so either
> 
> * none of the modules have debug-info, which happens when the build is in release mode. EDIT: actually, we always pass -g, even in release mode
> * all of the modules have debug-info, but some modules are so small that their debug-info is empty. Is that possible?

Compiling an empty module doesn't trigger the warning. Could you give details about the command triggering the warning ?

**Comment by pmwhite** [comment]
Inside `compiler/tests-jsoo`, we run the command
```
../bin-js_of_ocaml/js_of_ocaml.exe -I . -o ./jsoo_testsuite.cma.js --enable with-js-error --source-map-inline --pretty ./jsoo_testsuite.cma
```
Which spits out the warning twice. A lot of other commands have the same warning, but this one is representative.

**Comment by hhugo** [comment]
> Inside `compiler/tests-jsoo`, we run the command
> 
> ```
> ../bin-js_of_ocaml/js_of_ocaml.exe -I . -o ./jsoo_testsuite.cma.js --enable with-js-error --source-map-inline --pretty ./jsoo_testsuite.cma
> ```
> 
> Which spits out the warning twice. A lot of other commands have the same warning, but this one is representative.

Are you still running ocaml 4.12 ?

**Comment by hhugo** [comment]
How is `./jsoo_testsuite.cma` compiled ?

**Comment by hhugo** [comment]
@pmwhite, looking at old jenga-rules available on github, I suspect that you still don't pass `-g` when compiling `.ml-gen` to cmo.

**Comment by pmwhite** [comment]
> Are you still running ocaml 4.12 ?

No, 4.14 now.

> How is `./jsoo_testsuite.cma` compiled ?

This is the slightly sanitize version of the command that the build system runs.
```
ocamlc.opt -w @a-4-29-40-41-42-44-45-48-52-56-58-59-66-67-69-70 -strict-sequence -short-paths -strict-formats -g -error-style short -bin-annot -compat-32 jsoo_testsuite__.cmo jsoo_testsuite__Calc_parser.cmo jsoo_testsuite__Calc_lexer.cmo jsoo_testsuite__Parser_1307.cmo jsoo_testsuite__Lexer_1307.cmo jsoo_testsuite__Gh_1307.cmo jsoo_testsuite__Test_bigarray.cmo jsoo_testsuite__Test_channel.cmo jsoo_testsuite__Test_floats.cmo jsoo_testsuite__Test_fma.cmo jsoo_testsuite__Test_ints.cmo jsoo_testsuite__Test_io.cmo jsoo_testsuite__Test_marshal.cmo jsoo_testsuite__Test_obj.cmo jsoo_testsuite__Test_parsing.cmo jsoo_testsuite__Test_rec_mod.cmo jsoo_testsuite.cmo -cclib -ljsoo_testsuite_stubs -a -o jsoo_testsuite.cma
```

**Comment by hhugo** [comment]
> @pmwhite, looking at old jenga-rules available on github, I suspect that you still don't pass `-g` when compiling `.ml-gen` to cmo.

Check the command generating `jsoo_testsuite__.cmo`

**Comment by hhugo** [comment]
@pmwhite, My last commit disable the feature by default so that the PR can be release without silently breaking inline_tests with dune. For testing you can enable it with the `--enable auto-link` flag to `js_of_ocaml link`.

**Comment by pmwhite** [comment]
I realized I may not be understanding what this PR actually does. I was under the impression that we already were trimming unnecessary files, and that this moved the granularity down to the module level instead (this is just based on the description - I haven't read the code in the PR). However, now I'm thinking that this actually merely extends the tree-shaking from whole-program compilation into separate compilation as well. Is that the right way to think about it? Are the inclusion semantics for whole and separate compilation now exactly the same?

**Comment by hhugo** [comment]
> Are the inclusion semantics for whole and separate compilation now exactly the same?

This is the indent 

> However, now I'm thinking that this actually merely extends the tree-shaking from whole-program compilation into separate compilation as well. Is that the right way to think about it?

Both whole program compilation and separate compilation perform some deadcode elimination based on what they know. The DCE should not remove any side-effects.

When doing whole program compilation, we rely on the link ouput of ocamlc which does drop unused compilations units present in cma files. This PR implement the same drop logic inside jsoo when doing separate compilation.

**Comment by pmwhite** [comment]
Just as an update on the testing of this PR: I've not yet done all the testing I plan to, since it's a bit of work to get the build system to pass link-all in the right places. I'll update this thread when I eventually get to it.

**Comment by hhugo** [comment]
> Just as an update on the testing of this PR: I've not yet done all the testing I plan to, since it's a bit of work to get the build system to pass link-all in the right places. I'll update this thread when I eventually get to it.

Any update?

**Comment by pmwhite** [comment]
@hhugo No, not yet. It's on my stack of things to do, but I haven't gotten around to it yet.

**Pull request merged**
