### PR TITLE
Ppx: switch ppx_deriving_json to ast 408

### PR DESCRIPTION
**Pull request by hhugo**

### CODE REVIEW

**Comment by hhugo** [comment]
Blocked until `ppx_expect` is compatible with ppxlib.0.9

**Comment by xvw** [comment]
Ppx_expect is now compatible with `ppxlib.0.9`.

**Comment by hhugo** [comment]
The latest official version `v0.12.0` is still not compatible with `ppxlib.0.9`

**Comment by xvw** [comment]
Ah sorry :)

**Pull request merged**
