### PR TITLE
biome: enable all performance rules

### PR DESCRIPTION
**Pull request by smorimoto**

### CODE REVIEW

**Comment by smorimoto** [comment]
Found some regular expression warnings: https://github.com/ocsigen/js_of_ocaml/actions/runs/12069505071/job/33656910919?pr=1749#step:4:1

**Comment by hhugo** [comment]
Why is the CI not failing, can we make it fail ?

**Comment by smorimoto** [comment]
The `all` option will be removed in the future...
- https://github.com/biomejs/biome/pull/4664

**Comment by smorimoto** [comment]
> Why is the CI not failing, can we make it fail ?

I think it's because the rule is treated as a warning by default.

Of course we can make it an error.

**Comment by hhugo** [comment]
Did you close the PR on purpose ? Can you explain why ?

**Pull request closed without merging**
