### PR TITLE
The async keyword should not be followed by a newline

### LINKED ISSUE #1514: [BUG] Compiling using `--profile=release` leads to runtime errors
**Describe the bug**
At @funkywork, we're working on a collection of tools to interact with Tezos. We recently realized that when using our libraries, producing JavaScript artifacts with the `release` profile generates incorrect JavaScript output. For example, in this project (I think it's pretty minimal):  https://github.com/funkywork/tezos-dapps-examples/tree/main.
Using `dune build; dune exec bin/server/dapps.exe` and going to http://localhost:8888/dapps/connect launch properly the apps. But if you run `dune build --profile=release; dune exec bin/server/dapps.exe` you will have an error console: 

```
12:10:45.847 Uncaught SyntaxError: missing ) after argument list client.bc.js:4635
12:10:45.848 Uncaught ReferenceError: nightmare_js is not defined
    <anonymous> http://localhost:8888/dapps/connect:2
connect:2:358
12:10:45.848 Uncaught ReferenceError: nightmare_js is not defined
    <anonymous> http://localhost:8888/dapps/connect:2
connect:2:465
```

And here is the client.bc.js generated: https://gist.githubusercontent.com/xvw/d679d490d085e671f926e106cfff37b5/raw/69c2c552065c0466a93a4c05b323ccf75c6ef01a/client.bc.js

From a development point of view, this isn't a problem, but it does make it difficult to put things into production, as the non-release bundle weighs in at ~16mb, compared with ~2mb for release.

If I can provide any additional information, or create a smaller example, please don't hesitate to ask!

**Versions**
- `ocaml`: `5.0.0`
- `js_of_ocaml`: `5.4.0+git-e0d000e-dirty`

### PR DESCRIPTION
**Pull request by vouillon**
Fixes #1514

### CODE REVIEW

**Comment by xvw** [comment]
Hi @vouillon 
I have try your fix on https://github.com/funkywork/yourbones/tree/main/examples and I still have an issue related to that kind of line:

```
this.connection.open(a),a=this.connection),this.connection=this.setConnection(a),await
```

in https://gist.github.com/xvw/767a6e2ad72bff091b594a542d3cc744
So I guess that the fix should be applied to `await` too.

**Comment by vouillon** [comment]
@xvw I missed a case. An `async` at the end of the line is not recognized as a keyword, and thus we get an error at the following `await`.

**Comment by hhugo** [comment]
@vouillon, I've added some tests added more fixes. I also rebased  your branch.

**Comment by hhugo** [comment]
I see a different line for line number 4875
```js
window&&void
```

**Comment by xvw** [comment]
Ok, using a fixed commit (930234343cc18cd3d640a51656f43f741f3ef728) it is working! Thanks a lot!

**Pull request merged**
