### PR TITLE
Mutation observers API: https://dom.spec.whatwg.org/#mutation-observers

### PR DESCRIPTION
**Pull request by slegrand45**
A proposal for a binding to the mutation observers API. See also https://github.com/ocsigen/js_of_ocaml/issues/250

### CODE REVIEW

**Comment by vasilisp** [comment]
Thanks!

Could you rebase d212aebba6931231b65e1a8b02bee6b0aa5be405 on top of master to keep the history cleaner?

The API is a bit too raw JS for my taste. You can expose an OCaml-friendlier function that accepts the callback plus optional fields for the `_MutationObserverInit` fields, and calls the constructor internally. But that's just my opinion; maybe the binding is low-level on purpose.

**Comment by slegrand45** [comment]
I added a higher level OCaml function and the rebase is done.

**Comment by vouillon** [comment]
For the class type, I would use `mutationObserver` rather than `_MutationObserver`.

**Comment by slegrand45** [comment]
_MutationObserver renamed to mutationObserver.

**Comment by vouillon** [comment]
Great! Thanks!

**Pull request merged**
