### PR TITLE
Compiler: fix #599

### LINKED ISSUE #599: An equivalent of emscripten's MODULARIZE
Hi there,

Following up on the mailing list thread: `--wrap-in-func` seems to be pretty close to what I need (thanks!), except for the fact that it doesn't export the function itself in the global namespace (so I guess it could be useful from `eval`, but not from e.g. `importScripts` in a web worker.

The idea of emscripten's `modularize` is that loading the script exports (in the node.js case) or adds to the global namespace (in the brwoser case) a single function, which when called returns an instance of the program.  This is especially useful when the program has global state, since it gives you an easy way to reset it without reloading (and thus reparsing) the entire script.

Thanks!

### PR DESCRIPTION
**Pull request by hhugo**
@cpitclaudel, this is a quick attempt at addressing https://github.com/ocsigen/js_of_ocaml/issues/599.

### CODE REVIEW

**Comment by cpitclaudel** [comment]
Looks very nice! And IIUC, I can pass it an arbitrary (possibly empty) object instead of "window" to populate that object, right?

**Comment by cpitclaudel** [comment]
Tested; it works very nicely, thanks!
I also noticed after reverting to 2.8.4 that this could be emulated with `--wrap-in-fun --custom-header="var JSOO_FStar="`

**Comment by hhugo** [comment]
indeed :)
Can you describe a bit more your use case ?

**Comment by cpitclaudel** [comment]
Yes, of course.  I'm transpiling F* to Javascript, starting with the simplest possible interface (passing F* a bunch of command line arguments and a file), and printing the verification results.

One of the issues is that F* has a lot of global state, so calling main twice doesn't work: F* just gets very confused.  Instead, I need to reload F* every time.

One way to do this is to use a new WebWorker for each iteration; this isn't free, however, because if forces us to reload and reparse the Javascript every time.

A much better alternative is to have a factory function, FStar_JSOO, which can be called to instantiate a new, pristine instance of F*.  That factory is exactly what jsoo builds; I just need to grab it by name :)

**Comment by ejgallego** [comment]
@hhugo would you mind documenting how to get the old behavior back? I'm afraid I can't understand the current documentation. What is `VAL`?

**Comment by ejgallego** [comment]
In particular if using `--wrap-with-fun=` no parenthesis are generated thus using eval on the resulting code will result in a JS parsing error. Should we then do the wrapping client-side?

**Pull request merged**
