### PR TITLE
Make all tests pass on windows

### PR DESCRIPTION
**Pull request by hhugo**
will include/extends #1125 
- [x] properly detect absolute path on windows
- [x] make windows failure hard errors on windows 
- [x] fix toplevel on windows
- [x] fix expect test on window
- [x] fix all other tests on windows

### CODE REVIEW

**Review by smorimoto — APPROVED** [review]

**Comment by hhugo** [comment]
I'm going to fix the windows build before merging

**Comment by hhugo** [comment]
Expect test are still broken

**Comment by smorimoto** [comment]
By doing the same thing, I think you can fix it without making patches.
https://github.com/ocaml/ocaml-lsp/blob/b841d46f6a4bbb0719a3a726c020959a5e4868e2/.github/workflows/build-and-test.yml#L27

**Comment by hhugo** [comment]
> By doing the same thing, I think you can fix it without making patches.
> https://github.com/ocaml/ocaml-lsp/blob/b841d46f6a4bbb0719a3a726c020959a5e4868e2/.github/workflows/build-and-test.yml#L27

If this is enough, I feel it should be documented on the ppx_expect repo.

**Comment by hhugo** [comment]
Will merge once CI is green

**Pull request merged**
