### PR TITLE
Compiler: support for OCaml GPR#1568

### PR DESCRIPTION
**Pull request by hhugo**
Generalization of https://github.com/ocsigen/js_of_ocaml/pull/402

GPR#1568 allows exception-patterns under or-patterns 
See https://github.com/ocaml/ocaml/pull/1568

### CODE REVIEW

**Comment by hhugo** [comment]
@vouillon, do you have some time to review this ?

**Comment by hhugo** [comment]
I've reworked the PR into multiple commits.
One should mostly review the last one  https://github.com/ocsigen/js_of_ocaml/pull/642/commits/ccbcace2f541622659233998a38132f5b58ecc70

**Comment by hhugo** [comment]
```ocaml
exception A of int
let y =
  match Random.int 2 with
  | 0 as i | exception A (2 as i) -> i
  | i -> i+1
  | exception A i -> i+2
```
Compiles to
```javascript
    try
     {var _e_=caml_call1(Random[5],2),switch$0=0}
    catch(_f_)
     {_f_ = caml_wrap_exception(_f_);
      if(_f_[1] !== _a_)throw _f_;
      var _b_=_f_[2];
      if(2 === _b_)var _c_=_b_,switch$0=1;else var _d_=_b_ + 2 | 0,switch$0=2}
    switch(switch$0)
     {case 0:
       if(0 === _e_)
        var _c_=_e_,switch$1=0;
       else
        var _d_=_e_ + 1 | 0,switch$1=1;
       break;
      case 1:var switch$1=0;break;
      default:var switch$1=1}
    if(! switch$1)var _d_=_c_;
```
and 
```ocaml
exception A of int
let y =
  match Random.int 2 with
  | 0 as i | exception A (2 as i) -> i
  | i -> i+1
```
compiles to
```javascript
    try
     {var _e_=caml_call1(Random[5],2),switch$0=0}
    catch(_f_)
     {_f_ = caml_wrap_exception(_f_);
      if(_f_[1] === _a_)
       {var _b_=_f_[2];
        if(2 === _b_)var _c_=_b_,switch$0=1,switch$1=0;else var switch$1=1}
      else
       var switch$1=1;
      if(switch$1)throw _f_}
    if(switch$0)
     var switch$2=0;
    else
     if(0 === _e_)var _c_=_e_,switch$2=0;else var _d_=_e_ + 1 | 0,switch$2=1;
    if(! switch$2)var _d_=_c_;
```

**Comment by hhugo** [comment]
`$ jbuilder build @compiler/tests/runtest`
`$ cat _build/default/compiler/tests/bytecode/match_with_exn1.js`
`$ cat _build/default/compiler/tests/bytecode/match_with_exn2.js`

**Comment by hhugo** [comment]
I've added extra tests in 96ad7b84ef2d5e3d7bbcee98c52a8d89f8427054.
we can't include them in master. 
```
opam remote add ocaml-pr https://github.com/ocaml/ocaml-pr-repository.git
opam switch 4.06.0+pr1568
opam install js_of_ocaml-compiler
git checkout origin/ocaml-1568-test
jbuilder build @compiler/tests/runtest
```

**Comment by vouillon** [comment]
This looks good.

**Pull request merged**
