### PR TITLE
Runtime: no longer use arguments

### PR DESCRIPTION
**Pull request by hhugo**
subset of #1682

### CODE REVIEW

**Comment by hhugo** [comment]
@TyOverby, could you test this ?

**Comment by hhugo** [comment]
@TyOverby, if we end up merging this, we should probably also merge stdlib_modern.js and stdlib.js and get rid of stdlib_modern.js

**Comment by hhugo** [comment]
@TyOverby, Wasm support has been merged. I hoping that it means you can now easily test this PR ?

**Review by smorimoto — APPROVED** [review]

**Comment by smorimoto** [comment]
This should help simplify and increase runtime performance (a bit)

**Comment by hhugo** [comment]
@vouillon, any opinion here ?

**Review by vouillon — APPROVED** [review]
I'm not sure about the performance. This looks good otherwise.

**Pull request merged**
