### PR TITLE
Bench: revert f985d962db91c35bd4b4224edd9f89c51bf4a6d9

### PR DESCRIPTION
**Pull request by hhugo**

### CODE REVIEW

**Comment by hhugo** [comment]
@OlivierNicole, since you're playing with benchmarks, can you test this change ?

This is a revert of an old commit of mine, plus some doc.

**Comment by OlivierNicole** [comment]
I can run the benchmarks (it works), but I’m not sure if you want me to do something more.

**Comment by hhugo** [comment]
> I can run the benchmarks (it works), but I’m not sure if you want me to do something more.

running the benchmarks and generate the report should be enough.
Can you try generating reports ?

**Comment by OlivierNicole** [comment]
Yes, it works.

**Pull request merged**
