### PR TITLE
Add the Jstable module

### PR DESCRIPTION
**Pull request by Drup**
This module is backported from Eliom where it lived a very quiet life since its original commit 4 years ago.

For now, It's exactly the same as the one that was in eliom, but I think it would be interesting to see if there is a faster solution now.
@hhugo, I believe you did several such benchmark, any insights ?

I also wonder if we should change the API a little bit, so that to (partially) respect Hashtbl.S, but I'll wait for the above question to be answered first.

### CODE REVIEW

**Comment by vasilisp** [comment]
Good discovery :). I had never seen this. It definitely needs to move out of Eliom.

The implementation is weird from an OCaml point of view, but it seems like JS objects were used as tables at one point in time. What about [maps](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map)?

**Comment by Drup** [comment]
@vasilisp Considering the support on IE, that's not a great idea.

**Comment by Drup** [comment]
However, according to [this](http://kangax.github.io/compat-table/es5/#es5shim), it's probably fine to use `Object.create(null)` and get rid of the underscores.

**Comment by vasilisp** [comment]
OK. I guess you can commit what you have now for the move to happen, and we can improve it later.

In a related note, most of `Eliommod_dom` should be fused into the DOM-related JSOO modules, right?

**Comment by Drup** [comment]
I haven't looked at dom stuff at all.

**Comment by zakki** [comment]
Don't `Jstable.find` need `hasOwnProperty` check?

**Comment by vasilisp** [comment]
@zakki, I think it is OK. It returns `'a Js.Optdef.t`, so the caller is obliged to check whether the result is defined or not, e.g., via `Js.Optdef.test`.

**Comment by zakki** [comment]
@vasilisp I think it has some corner cases. 
```ocaml
let _ =
  let a = Jstable.create() in
  let v = Jstable.find a (Js.string "__proto_") in (* expected? *)
  Firebug.console##log(v)
```

**Comment by Drup** [comment]
That is more-or-less expected, yes. We could solve it by using `Obj.create(null)` as mentioned earlier.

**Pull request merged**
