### PR TITLE
For debugging, print escaped variables before allocating names

### PR DESCRIPTION
**Pull request by OlivierNicole**
This is a fix to #1448. Currently, when some variables escape, we print their names after calling `Strategy.allocate`; as a result those escaped names no longer appear in the program and the debug output is unhelpful. This prints the program before allocating new names.

### CODE REVIEW

**Comment by hhugo** [comment]
> as a result those escaped names no longer appear in the program and the debug output is unhelpful. 

I have to disagree.

#1448 allocate variables first so that only unbound/unallocated variable appear  in the `<_eF_>` form;

**Comment by OlivierNicole** [comment]
Then I am not sure where the problem lies exactly, but with #1448 I had a message `Some variables escaped: aF_e`, but the name `<aF_e>` was nowhere to be found in the printed program.

**Comment by hhugo** [comment]
> ```diff
> +  IdentSet.iter
> +    (function
> +      | S _ -> ()
> +      | V x -> names.(Var.idx x) <- "")
> +    free;
> ```

I've pushed the diff on master

**Comment by hhugo** [comment]
Closing. Please open a new issue or PR is you're experiencing more issues

**Pull request closed without merging**
