### PR TITLE
Lwt_js_events: added `passive` option. Dom, Dom_html: added customEvent and pointer events

### PR DESCRIPTION
**Pull request by monstasat**
## `passive` argument for `Lwt_js_events` 
Added `passive` optional argument to all relevant functions of `Lwt_js_events` module

## Pointer events
* Added `pointerEvent` type (see [MDN](https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent))
* Added pointer event types to `Dom_html.Event` module
* Added helper functions for pointer events handling to `Lwt_js_events` module
* Added pointer event related methods to `eventTarget` object type

## CustomEvent
* Added `customEvent` object type
* Added `Dom.createCustomEvent` and `Dom_html.createCustomEvent` helper functions to allow creation of custom events
* Added `eventTarget##dispatchEvent` method to allow dispatching of custom (and other) events

### CODE REVIEW

**Comment by monstasat** [comment]
Hey there! Are there any plans on merging this? Any comments?

**Comment by hhugo** [comment]
Theses changes would be easier to review in 3 different PR. Would you mind splitting ?

**Comment by monstasat** [comment]
Sure.

**Comment by monstasat** [comment]
Has split this into separate PRs. Closing.

**Pull request closed without merging**
