### PR TITLE
Runtime: clean jsoo_static_env

### PR DESCRIPTION
**Pull request by hhugo**

### CODE REVIEW

**Comment by hhugo** [comment]
@TyOverby, could you check in what context `jsoo_static_env` is used in the Janestreet codebase ?

**Comment by hhugo** [comment]
ping @TyOverby

**Comment by TyOverby** [comment]
I'll check into this on Monday

**Comment by TyOverby** [comment]
The only usage of jsoo_static_env (outside of our vendored copy jsoo) is located here: https://github.com/janestreet/timezone/blob/master/src/runtime.js

**Pull request closed without merging**
