### PR TITLE
Runtime: os_type: Cygwin -> Win32

### PR DESCRIPTION
**Pull request by hhugo**

### CODE REVIEW

**Comment by hhugo** [comment]
@phated, would you mind checking if this PR works for `grain` ? It should only affect windows.

**Review by phated — COMMENTED** [review]
@hhugo sorry for the delay. We actually override the Cygwin value to Win32 already. See https://github.com/grain-lang/grain/blob/416936b08015d4bf0e945860b646bfa00e2f14b3/compiler/src/utils/hacks.js#L4

So this should be a good change for Grain.

**Comment by hhugo** [comment]
Cool, do you need the rest of the stubs ? I thought they were present in jsoo already.

**Comment by phated** [comment]
I think they are overrides related to `\` path separators instead of `/`

**Comment by hhugo** [comment]
This PR now accepts both `/` and `\`. Could you try dropping your overrides with jsoo master and report if something still needs to be fixed ?

**Comment by phated** [comment]
I'd love to try it, but we never solved the performance problems so our test suite doesn't complete. I forget which older version we needed to pin.

**Comment by hhugo** [comment]
Can you try again and reopen an issue for the perf issue ?

**Pull request merged**
