### PR TITLE
Runime: add support for Str

### LINKED ISSUE #315: Provide the runtime for str
translate https://github.com/ocaml/ocaml/blob/trunk/otherlibs/str/strstubs.c to JavaScript

### PR DESCRIPTION
**Pull request by hhugo**
Should fix #315 
 
This is based on a work started for jscoq https://github.com/jscoq/jscoq/blob/v8.11/coq-js/js_stub/str.js

- [x] import test from the OCaml distribution
- [x] import test from the ocaml-re (re vs str)
- [x] support for forward & backward search
- [x] support for partial match
- [x] support replacement

### CODE REVIEW

**Comment by hhugo** [comment]
cc @ejgallego @corwin-of-amber

**Comment by hhugo** [comment]
@corwin-of-amber, would you like to help review this ?

**Comment by corwin-of-amber** [comment]
Sure!

**Comment by hhugo** [comment]
@corwin-of-amber, thanks. I'll wait for your feedback.

**Comment by corwin-of-amber** [comment]
May be unrelated, but I had to upgrade `lwt` to compile this branch (I had 4.4.0). Do you need to update the opam file perhaps?

**Comment by corwin-of-amber** [comment]
Looks very thorough @hhugo. I tested it with jsCoq, and it successfully replaces our original `str.js`. (Although the needs of jsCoq in terms of regexes are quite meagre).

**Comment by corwin-of-amber** [comment]
Is `js_of_ocaml.ppx` deprecated and should be replaced by `js_of_ocaml-ppx`?

**Comment by hhugo** [comment]
> Is `js_of_ocaml.ppx` deprecated and should be replaced by `js_of_ocaml-ppx`?

Yes. `js_of_ocaml.ppx` had been a compatibility proxy for  `js_of_ocaml-ppx`
for long enough. It was removed recently I think

**Comment by hhugo** [comment]
> May be unrelated, but I had to upgrade `lwt` to compile this branch (I had 4.4.0). Do you need to update the opam file perhaps?

Possible, I'll take a look

**Comment by hhugo** [comment]
@corwin-of-amber, I've managed to compile with `lwt.4.4.0` without problems

**Comment by corwin-of-amber** [comment]
Ok, it may have been the case that I had an even earlier version? Or some other problem that prevented me from compiling initially. Don't worry about it then :)

**Pull request merged**
