### PR TITLE
ppx: support for optdef_prop, writeonly_prop, ..

### LINKED ISSUE #645: Add support for Js.optdef_prop in PPX syntax
It would be nice to be able to create properties of type `Js.optdef_prop` from the PPX syntax.

I open this feature request as requested by @Drup here: https://stackoverflow.com/a/48471824/1160770. :)

> I don't remember implementing, and I doubt it was added later.
> 
> IIRC, One of the reason was that there was no easy syntax to use, but I could have just used an attribute. Another was that it didn't seem that useful at the time, but I guess I was wrong. :)
> 
> Please make a feature request on the bug tracker.

### PR DESCRIPTION
**Pull request by hhugo**
fix #645

### CODE REVIEW

**Comment by Drup** [comment]
From a casual read, this looks good. The implementation seems complete and straightforward. You didn't documented the new attributes, though.

**Comment by hhugo** [comment]
I've extended the support for `optdef_prop`.
One can do
```ocaml
object
  val p1 = Js.undefined [@@optdef]
  val p2 = Js.def 2 [@@optdef]
  val p3 = 2 [@@optdef_return]
end
```

**Comment by hhugo** [comment]
I'm not super exited by `[@@optdef_return]`. Any other proposal ?

**Comment by Drup** [comment]
I suppose you mean the name of the attribute? Me neither, but I don't have a better proposal. Maybe use a `.` instead of the `_`. We could also not have it at all, since it's not really essential.

**Comment by hhugo** [comment]
I will probably just remove it.

**Comment by hhugo** [comment]
Thanks for the review.

**Pull request merged**
