### PR TITLE
Make phys_equal more like native

### LINKED ISSUE #1372: Use `Object.is` instead of `===` to implement phys_equal
There are a few places where the behavior of `phys_equal` differ between native OCaml and Jsoo: 

| a   | b    | native | jsoo  |
|-----|------|--------|-------|
| NaN | NaN  | true   | false |
| 0.0 | -0.0 | false  | true  |

The (relatively) new `Object.is` function implements those comparisons "correctly":
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is

### PR DESCRIPTION
**Pull request by hhugo**
Fix #1372

### CODE REVIEW

**Comment by hhugo** [comment]
This change revealed some issues with some js stubs what were returning `-0` instead of `0`.

**Review by TyOverby — APPROVED** [review]

**Comment by hhugo** [comment]
@ty, is there any per difference between the two ? Is `object.is` available everywhere?

**Comment by TyOverby** [comment]
https://caniuse.com/mdn-javascript_builtins_object_is

It’s pretty widely supported!

**Comment by TyOverby** [comment]
As for performance impacts, I don't have a good intuition for if it would be faster or slower.  A small microbenchmark that I just made seems to indicate that `Object.is` is faster 

image

**Comment by hhugo** [comment]
I'm not really happy with the current implementation, mostly because the decision to use `===` or `Object.is` is syntactic.
@vouillon, any opinion ?

**Comment by hhugo** [comment]
> I'm not really happy with the current implementation, mostly because the decision to use `===` or `Object.is` is syntactic. @vouillon, any opinion ?

I've changed the implementation. We now keep track of whether `Eq` and `Neq` compare float or non-float values.

**Review by TyOverby — APPROVED** [review]

**Comment by vouillon** [comment]
I'm not sure how much of a difference this PR makes. In most cases, the physical equality will still not behave the same. For instance, this will still return `true` with Js_of_ocaml:
```ocaml
# 0. == 0.;;
- : bool = false
```

**Comment by hhugo** [comment]
> I'm not sure how much of a difference this PR makes. In most cases, the physical equality will still not behave the same. For instance, this will still return `true` with Js_of_ocaml:
> 
> ```ocaml
> # 0. == 0.;;
> - : bool = false
> ```

The most interesting bit is "fixing" `phys_equal` between `0.` and `-0.`.
The rest (whether two identical float are equal or not) can been seen as  an implementation detail.

That said, looking at the documentation of `==`, `0. == -0.` is fine.
```
   On non-mutable types, the behavior of [( == )] is
   implementation-dependent; however, it is guaranteed that
   [e1 == e2] implies [compare e1 e2 = 0].
 ```

**Pull request closed without merging**
