### PR TITLE
Support reproducible builds by using "BUILD_PATH_PREFIX_MAP"

### PR DESCRIPTION
**Pull request by xclerc**

### CODE REVIEW

**Comment by xclerc** [comment]
Tentative fix for https://github.com/ocsigen/js_of_ocaml/issues/714.

**Comment by hhugo** [comment]
I get 
```
Error: Files /home/hugo/.opam/4.07.1/lib/build_path_prefix_map/build_path_prefix_map.cmxa
       and /home/hugo/.opam/4.07.1/lib/ocaml/compiler-libs/ocamlcommon.cmxa
       both define a module named Build_path_prefix_map
```

**Comment by hhugo** [comment]
@gasche, it seems that build_path_prefix_map cannot be used together with compiler-libs.common because of name conflict

**Comment by xclerc** [comment]
I have pushed a new version that (i) vendors the module
(avoiding a conditional dependency), and (ii) applies the
rewrite to all path values in the source map.

(I still have to double-check there is no regression.)

**Comment by xclerc** [comment]
The Travis builds seem to be broken after https://github.com/ocsigen/js_of_ocaml/commit/c0fd99bf852ca010baa2bfa2affdd1811f031e5f,
because the opam files are now 2.0 while the opam
used by the Travis jobs is still 1.2.

**Comment by hhugo** [comment]
I fixed travis. Can you rebase this PR ?

**Comment by xclerc** [comment]
Commit https://github.com/ocsigen/js_of_ocaml/pull/719/commits/a356e65eb716494ba045e5b1c44429e3752628ec adds a test demonstrating the effect of this PR.

It is not very satisfying, most notably because it goes through a
shell script to execute `js_of_ocaml`. It does so to access the
current working directory, and also to ensure that only this part of
the test is affected by the `BUILD_PATH_PREFIX_MAP` environment
variable.

**Comment by hhugo** [comment]
merged manually. Thanks

**Comment by xclerc** [comment]
Great; thanks!

**Pull request closed without merging**
