### PR TITLE
Alternative to #1577

### PR DESCRIPTION
**Pull request by hhugo**
Cons: ~~breaks 2/3 packages (ppx_expect, alcotest)~~
Pro: no override logic

### CODE REVIEW

**Comment by hhugo** [comment]
@tkluck-janestreet, would you have time to look at this PR. The latest version no longer break compatibility with ppx_expect thanks to js `Proxy`. Can you confirm it works for you ?

**Comment by tkluck-janestreet** [comment]
Hi @hhugo it's looking good so far. I'm running it on our continuous integration and will report the results here on Monday. I'd be surprised if it's going to uncover any problems.

**Comment by tkluck-janestreet** [comment]
I was too optimistic; unfortunately using `Symbol`s as keys to a `WeakMap` is a [relatively new feature](https://github.com/nodejs/node/issues/49135) and it doesn't work on the version of node that I'm using.

Not saying I wouldn't be happy if you merged this. Do you have a policy about which javascript versions are supported?

**Comment by hhugo** [comment]
> I was too optimistic; unfortunately using `Symbol`s as keys to a `WeakMap` is a [relatively new feature](https://github.com/nodejs/node/issues/49135) and it doesn't work on the version of node that I'm using.
> 
> Not saying I wouldn't be happy if you merged this. Do you have a policy about which javascript versions are supported?

No policy, I just try to be reasonable.
So it seems that this doesn't work with node 18 which is still in maintenance mode until April 2025. I think it would be unfortunate to break such setup. Let's try something else, this PR was mostly a hack to avoid breaking 2 packages after all.

I think it's a better long term solution to break and fix ppx_expect and alcotest and come up with a better abstraction/api/helper inside jsoo.

**Pull request closed without merging**
